In [ ]:
import numpy as np
npmas = np.ones((8, 8)).astype(int)
npmas[::2,::2]=np.zeros((4, 4))
npmas[1::2,1::2]=np.zeros((4, 4))
npmas

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
npmas = np.tile(np.arange(5), (5, 1))
npmas

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
npmas = np.random.rand(3,3,3)
npmas

array([[[0.31074592, 0.30772103, 0.39225983],
        [0.59204899, 0.11890018, 0.16242477],
        [0.8056595 , 0.57054651, 0.39338051]],

       [[0.69227663, 0.39086792, 0.22495305],
        [0.27294963, 0.06170429, 0.3313805 ],
        [0.85164549, 0.66830862, 0.61154553]],

       [[0.8690959 , 0.07376744, 0.18229847],
        [0.43164926, 0.49377817, 0.16780876],
        [0.59481855, 0.08122043, 0.40388169]]])

In [ ]:
n = int(input())
m = int(input())
npmas = np.zeros((n,m)).astype(int)
npmas[::,:1:]=np.ones((n,1))
npmas[::,-1::]=np.ones((n,1))
npmas[0]=np.ones(m)
npmas[n-1]=np.ones(m)
npmas

4
5


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
npmas = np.random.rand(20)
npmas=np.sort(npmas)[::-1]
npmas

array([0.96037305, 0.79142153, 0.77774349, 0.75722091, 0.70154544,
       0.68304739, 0.60514164, 0.51343749, 0.5051837 , 0.492856  ,
       0.48823194, 0.47773749, 0.44819169, 0.38114887, 0.37108824,
       0.18028996, 0.06970938, 0.04375052, 0.02825795, 0.02240752])

In [ ]:
npmas = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(npmas)
print("Форма:", npmas.shape)
print("Размер:", npmas.size)
print("Размерность:", npmas.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма: (3, 4)
Размер: 12
Размерность: 2


In [ ]:
import pandas as pd
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])
distance = ((a - b) ** 2).sum() ** 0.5
distance

5.196152422706632

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/refs/heads/main/airline_passenger_satisfaction.csv")
data.head()

Gender      customer_type  age   type_of_travel customer_class  \
0    Male     Loyal Customer   13  Personal Travel       Eco Plus   
1    Male  disloyal Customer   25  Business travel       Business   
2  Female     Loyal Customer   26  Business travel       Business   
3  Female     Loyal Customer   25  Business travel       Business   
4    Male     Loyal Customer   61  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
0              460                      3                                  4   
1              235                      3                                  2   
2             1142                      2                                  2   
3              562                      2                                  5   
4              214                      3                                  3   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
0                       3              1  ...                       5   
1                       3              3  ...                       1   
2                       2              2  ...                       5   
3                       5              5  ...                       2   
4                       3              3  ...                       3   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
0                4                 3                 4                4   
1                1                 5                 3                1   
2                4                 3                 4                4   
3                2                 5                 3                1   
4                3                 4                 4                3   

   inflight_service  cleanliness  departure_delay_in_minutes  \
0                 5            5                          25   
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   
4                 3            3                           0   

   arrival_delay_in_minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  
4                       0.0                satisfied  

[5 rows x 23 columns]

In [ ]:
data.tail()

Gender      customer_type  age   type_of_travel customer_class  \
129875    Male  disloyal Customer   34  Business travel       Business   
129876    Male     Loyal Customer   23  Business travel       Business   
129877  Female     Loyal Customer   17  Personal Travel            Eco   
129878    Male     Loyal Customer   14  Business travel       Business   
129879  Female     Loyal Customer   42  Personal Travel            Eco   

        flight_distance  inflight_wifi_service  \
129875              526                      3   
129876              646                      4   
129877              828                      2   
129878             1127                      3   
129879              264                      2   

        departure_arrival_time_convenient  ease_of_online_booking  \
129875                                  3                       3   
129876                                  4                       4   
129877                                  5                       1   
129878                                  3                       3   
129879                                  5                       2   

        gate_location  ...  inflight_entertainment  onboard_service  \
129875              1  ...                       4                3   
129876              4  ...                       4                4   
129877              5  ...                       2                4   
129878              3  ...                       4                3   
129879              5  ...                       1                1   

        leg_room_service  baggage_handling  checkin_service  inflight_service  \
129875                 2                 4                4                 5   
129876                 5                 5                5                 5   
129877                 3                 4                5                 4   
129878                 2                 5                4                 5   
129879                 2                 1                1                 1   

        cleanliness  departure_delay_in_minutes  arrival_delay_in_minutes  \
129875            4                           0                       0.0   
129876            4                           0                       0.0   
129877            2                           0                       0.0   
129878            4                           0                       0.0   
129879            1                           0                       0.0   

                   satisfaction  
129875  neutral or dissatisfied  
129876                satisfied  
129877  neutral or dissatisfied  
129878                satisfied  
129879  neutral or dissatisfied  

[5 rows x 23 columns]

In [ ]:
data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Gender                             129880 non-null  object 
 1   customer_type                      129880 non-null  object 
 2   age                                129880 non-null  int64  
 3   type_of_travel                     129880 non-null  object 
 4   customer_class                     129880 non-null  object 
 5   flight_distance                    129880 non-null  int64  
 6   inflight_wifi_service              129880 non-null  int64  
 7   departure_arrival_time_convenient  129880 non-null  int64  
 8   ease_of_online_booking             129880 non-null  int64  
 9   gate_location                      129880 non-null  int64  
 10  food_and_drink                     129880 non-null  int64  
 11  online_boarding                    1298

In [ ]:
data.describe()

age  flight_distance  inflight_wifi_service  \
count  129880.000000    129880.000000          129880.000000   
mean       39.427957      1190.316392               2.728696   
std        15.119360       997.452477               1.329340   
min         7.000000        31.000000               0.000000   
25%        27.000000       414.000000               2.000000   
50%        40.000000       844.000000               3.000000   
75%        51.000000      1744.000000               4.000000   
max        85.000000      4983.000000               5.000000   

       departure_arrival_time_convenient  ease_of_online_booking  \
count                      129880.000000           129880.000000   
mean                            3.057599                2.756876   
std                             1.526741                1.401740   
min                             0.000000                0.000000   
25%                             2.000000                2.000000   
50%                             3.000000                3.000000   
75%                             4.000000                4.000000   
max                             5.000000                5.000000   

       gate_location  food_and_drink  online_boarding   seat_comfort  \
count  129880.000000   129880.000000    129880.000000  129880.000000   
mean        2.976925        3.204774         3.252633       3.441361   
std         1.278520        1.329933         1.350719       1.319289   
min         0.000000        0.000000         0.000000       0.000000   
25%         2.000000        2.000000         2.000000       2.000000   
50%         3.000000        3.000000         3.000000       4.000000   
75%         4.000000        4.000000         4.000000       5.000000   
max         5.000000        5.000000         5.000000       5.000000   

       inflight_entertainment  onboard_service  leg_room_service  \
count           129880.000000    129880.000000     129880.000000   
mean                 3.358077         3.383023          3.350878   
std                  1.334049         1.287099          1.316252   
min                  0.000000         0.000000          0.000000   
25%                  2.000000         2.000000          2.000000   
50%                  4.000000         4.000000          4.000000   
75%                  4.000000         4.000000          4.000000   
max                  5.000000         5.000000          5.000000   

       baggage_handling  checkin_service  inflight_service    cleanliness  \
count     129880.000000    129880.000000     129880.000000  129880.000000   
mean           3.632114         3.306267          3.642193       3.286326   
std            1.180025         1.266185          1.176669       1.313682   
min            1.000000         0.000000          0.000000       0.000000   
25%            3.000000         3.000000          3.000000       2.000000   
50%            4.000000         3.000000          4.000000       3.000000   
75%            5.000000         4.000000          5.000000       4.000000   
max            5.000000         5.000000          5.000000       5.000000   

       departure_delay_in_minutes  arrival_delay_in_minutes  
count               129880.000000             129487.000000  
mean                    14.713713                 15.091129  
std                     38.071126                 38.465650  
min                      0.000000                  0.000000  
25%                      0.000000                  0.000000  
50%                      0.000000                  0.000000  
75%                     12.000000                 13.000000  
max                   1592.000000               1584.000000

In [ ]:
data.iloc[1:4].head()

Gender      customer_type  age   type_of_travel customer_class  \
1    Male  disloyal Customer   25  Business travel       Business   
2  Female     Loyal Customer   26  Business travel       Business   
3  Female     Loyal Customer   25  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
1              235                      3                                  2   
2             1142                      2                                  2   
3              562                      2                                  5   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
1                       3              3  ...                       1   
2                       2              2  ...                       5   
3                       5              5  ...                       2   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
1                1                 5                 3                1   
2                4                 3                 4                4   
3                2                 5                 3                1   

   inflight_service  cleanliness  departure_delay_in_minutes  \
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   

   arrival_delay_in_minutes             satisfaction  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  

[3 rows x 23 columns]

In [ ]:
data[data['age'] >= 30].head()

Gender   customer_type  age   type_of_travel customer_class  \
4     Male  Loyal Customer   61  Business travel       Business   
6     Male  Loyal Customer   47  Personal Travel            Eco   
7   Female  Loyal Customer   52  Business travel       Business   
8   Female  Loyal Customer   41  Business travel       Business   
12    Male  Loyal Customer   53  Business travel            Eco   

    flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
4               214                      3                                  3   
6              1276                      2                                  4   
7              2035                      4                                  3   
8               853                      1                                  2   
12              834                      1                                  4   

    ease_of_online_booking  gate_location  ...  inflight_entertainment  \
4                        3              3  ...                       3   
6                        2              3  ...                       2   
7                        4              4  ...                       5   
8                        2              2  ...                       1   
12                       4              4  ...                       1   

    onboard_service  leg_room_service  baggage_handling  checkin_service  \
4                 3                 4                 4                3   
6                 3                 3                 4                3   
7                 5                 5                 5                4   
8                 1                 2                 1                4   
12                1                 1                 3                4   

    inflight_service  cleanliness  departure_delay_in_minutes  \
4                  3            3                           0   
6                  5            2                           9   
7                  5            4                           4   
8                  1            2                           0   
12                 4            1                          28   

    arrival_delay_in_minutes             satisfaction  
4                        0.0                satisfied  
6                       23.0  neutral or dissatisfied  
7                        0.0                satisfied  
8                        0.0  neutral or dissatisfied  
12                       8.0  neutral or dissatisfied  

[5 rows x 23 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
data = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
scaler = MinMaxScaler()
data[['sepal_length_cm']] = scaler.fit_transform(data[['sepal_length_cm']])
scaler = StandardScaler()
data[['sepal_width_cm']] = scaler.fit_transform(data[['sepal_width_cm']])
data.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa